// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Silver_Inventory;

namespace Silver_Inventory.Migrations
{
    [DbContext(typeof(ChestContext))]
    [Migration("20191123011916_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Silver_Inventory.Item", b =>
                {
                    b.Property<int>("ItemNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChestName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Condition");

                    b.Property<string>("Description");

                    b.Property<string>("Grade");

                    b.Property<string>("GradingService");

                    b.Property<string>("ItemName");

                    b.Property<int>("ItemType");

                    b.Property<string>("ItemYear");

                    b.Property<decimal>("MeltAmount");

                    b.Property<string>("MintMark");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("NurismaticAmount");

                    b.Property<decimal>("PurchaseAmount");

                    b.Property<string>("PurchaseDate");

                    b.Property<string>("Strike");

                    b.HasKey("ItemNumber");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Silver_Inventory.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance");

                    b.Property<string>("ChestName");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("ItemNumber");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<int>("TransactionType");

                    b.HasKey("Id");

                    b.HasIndex("ItemNumber");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Silver_Inventory.Transaction", b =>
                {
                    b.HasOne("Silver_Inventory.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
